server:
  port: 0

spring:
  application:
    name: boardHigh
  config:
    activate:
      on-profile: dev
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/devwkrud
      driver-class-name: org.mariadb.jdbc.Driver
      username: devwkrud
      password: devwkrud
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 5
      max-lifetime: 240000
      maximum-pool-size: 20
      auto-commit: true # default true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

#mybatis:
#  config-location: classpath:config/mybatis-config.xml
#  mapper-locations: classpath:mapper/**/*.xml
#  type-aliases-package: com.wk.boardHigh

logging:
  level:
    root: info
    com.zaxxer.hikari.pool.HikariPool: debug